const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({headless:true,channel:'msedge'}),p=await b.newPage();let hits=[],errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.route('**/*',async r=>{const u=new URL(r.request().url());if(u.hostname==='wwwmacedalighting.netlify.app'){let name=u.pathname.endsWith('/')?u.pathname+'index.html':u.pathname;const f=path.join(process.cwd(),name);return r.fulfill({status:fs.existsSync(f)?200:404,body:fs.existsSync(f)?fs.readFileSync(f):'',contentType:f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html'});}if(u.hostname==='cdn.jsdelivr.net')return r.fulfill({contentType:'text/javascript',body:`window.quoteInserts=[];window.failUpload=false;window.failInsert=false;window.supabase={createClient:()=>({storage:{from:()=>({upload:async()=>({error:window.failUpload?Error('TEST upload'):null}),getPublicUrl:()=>({data:{publicUrl:''}})})},from:()=>({insert:async q=>{if(window.failInsert)return {error:Error('TEST insert')};window.quoteInserts.push(q);return {error:null}},select:()=>({eq:()=>({order:async()=>({data:[],error:null})})})})})};`});hits.push(u.href);return r.fulfill({contentType:'text/javascript',body:''});});
await p.goto('https://wwwmacedalighting.netlify.app/?utm_source=door_hanger&utm_medium=qr&utm_campaign=holiday_2026#quote');assert(!hits.some(x=>x.includes('googletagmanager')||x.includes('clarity.ms')));await p.getByRole('button',{name:'Allow analytics',exact:true}).click();assert(hits.some(x=>x.includes('googletagmanager')));assert(hits.some(x=>x.includes('clarity.ms')));
const events=()=>p.evaluate(()=>dataLayer.filter(x=>x[0]==='event').map(x=>({name:x[1],data:x[2]})));
await p.locator('#submitBtn').click();assert.equal(await p.evaluate(()=>quoteInserts.length),0);
for(const [id,value] of [['name','Private Test Name'],['phone','3235550123'],['email','private@example.invalid'],['address','123 Secret Test Street'],['message','Private message']])await p.locator('#'+id).fill(value);
assert.equal((await events()).filter(x=>x.name==='quote_form_start').length,1);assert.equal((await events()).filter(x=>x.name==='generate_lead').length,0);
await p.locator('#photos').setInputFiles({name:'PrivateName-photo.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/O4sAAAAASUVORK5CYII=','base64')});await p.locator('#smsOptIn').check();
await p.evaluate(()=>window.failUpload=true);await p.locator('#submitBtn').click();await p.waitForFunction(()=>!document.getElementById('submitBtn').disabled);assert.equal((await events()).filter(x=>x.name==='generate_lead').length,0);
await p.evaluate(()=>{window.failUpload=false;window.failInsert=true});await p.locator('#submitBtn').click();await p.waitForFunction(()=>!document.getElementById('submitBtn').disabled);assert.equal((await events()).filter(x=>x.name==='generate_lead').length,0);
await p.evaluate(()=>window.failInsert=false);await p.locator('#submitBtn').click();await p.waitForFunction(()=>quoteInserts.length===1);assert.equal((await events()).filter(x=>x.name==='generate_lead').length,1);assert.equal(await p.evaluate(()=>quoteInserts[0].marketing_attribution.utm_source),'door_hanger');await p.evaluate(()=>MLAnalytics.lead(quoteInserts[0].id,'homepage'));assert.equal((await events()).filter(x=>x.name==='generate_lead').length,1);
const serialized=JSON.stringify(await events());for(const secret of ['Private Test','3235550123','private@example','Secret Test','Private message','PrivateName-photo'])assert(!serialized.includes(secret),secret+' excluded');
assert.equal(await p.locator('#quoteForm').getAttribute('data-clarity-mask'),'true');
await p.locator('a[href="#quote"]').first().click();assert((await events()).some(x=>x.name==='quote_cta_click'));
await p.goto('https://wwwmacedalighting.netlify.app/visualizer/?utm_source=flyer');assert.equal(await p.evaluate(()=>MLAnalytics.attribution().utm_source),'door_hanger');
await p.goto('https://wwwmacedalighting.netlify.app/inbox/');assert.equal(await p.evaluate(()=>typeof MLAnalytics),'undefined');
for(const source of ['yard_sign','flyer']){await p.goto('https://wwwmacedalighting.netlify.app/');await p.evaluate(()=>localStorage.removeItem('mlFirstTouchV1'));await p.goto('https://wwwmacedalighting.netlify.app/?utm_source='+source+'&utm_medium=qr&utm_campaign=holiday_2026#quote');assert.equal(await p.evaluate(()=>MLAnalytics.attribution().utm_source),source)}
console.log('PASS: consent gate, GA/Clarity script requests, native validation, upload/insert failures, successful insert event once, three sources, navigation persistence, PII exclusion, masking and admin exclusion. All provider/quote requests mocked.');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
