export async function renderProductEngine(ctx){
 const {el,esc,authFetch,toast,openDetail}=ctx;
 const endpoint='https://gidqdlcvyasqalitqvcn.supabase.co/functions/v1/maceda-product-engine';
 const call=(action,data={})=>authFetch(endpoint,{method:'POST',body:JSON.stringify({action,...data})});
 const j=await authFetch(endpoint),p=j.provider;
 const status=v=>'<span class="badge '+(v==='in_maceda_inventory'?'good':'warn')+'">'+esc(v.replaceAll('_',' '))+'</span>';
 const options=(items,id='id',name='name')=>items.map(x=>'<option value="'+esc(x[id])+'">'+esc(x[name])+'</option>').join('');
 const purchaseLink=value=>{try{const u=new URL(value);return u.protocol==='https:'&&['amazon.com','www.amazon.com','business.amazon.com'].includes(u.hostname)?'<a class="secondary" href="'+esc(u.href)+'" target="_blank" rel="noopener noreferrer">Open supplier item — manual purchase</a>':''}catch{return ''}};
 const reload=()=>renderProductEngine(ctx);
 const action=async(fn,success)=>{try{await fn();toast(success);await reload()}catch(e){toast(e.message,'bad')}};
 const input=(label,name,value='',extra='')=>'<label>'+esc(label)+'<input class="field" name="'+name+'" value="'+esc(value)+'" '+extra+'></label>';
 const select=(label,name,html)=>'<label>'+esc(label)+'<select class="field" name="'+name+'">'+html+'</select></label>';
 el('content').innerHTML=`<style>
 .pe .secondary{display:inline-flex;align-items:center;justify-content:center;border:1px solid var(--line);border-radius:10px;background:#fff;padding:9px 12px;font:inherit;font-size:12px;font-weight:700;color:var(--forest2);text-decoration:none;cursor:pointer}.pe button:disabled{opacity:.45;cursor:not-allowed}.pe .primary{padding:10px 14px}.pe{max-width:1200px}.pe h2{font-family:Georgia,serif;font-size:28px;margin:0 0 10px}.pe p{color:var(--muted);line-height:1.6}.pe section{padding:22px;margin-bottom:18px}.pe-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.pe label{display:grid;gap:6px;font-size:12px;font-weight:700}.pe label:has(input[type=checkbox]){display:flex;align-items:center}.pe .field{width:100%;min-width:0}.pe-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:15px}.pe-card{border:1px solid var(--border,#e0e3da);border-radius:14px;padding:16px;min-width:0}.pe-card h3{margin:0 0 8px}.pe details{margin-top:15px}.pe summary{cursor:pointer;font-weight:700}.pe small{display:block;color:var(--muted);line-height:1.5;margin-top:6px}.pe textarea{min-height:80px}.pe button{min-height:40px}.pe .wide{grid-column:1/-1}.pe code{overflow-wrap:anywhere}.pe .pe-note{background:#f6f0df;border-left:3px solid var(--gold);padding:12px;border-radius:8px}.pe-list{display:grid;gap:12px}@media(max-width:620px){.pe-grid{grid-template-columns:1fr}.pe section{padding:16px}.pe h2{font-size:24px}}
 </style><div class="pe">
 <section class="panel"><h2>Maceda Product Engine</h2><p>A curated decoration catalog, verified inventory and purchase planning.</p>
 <div class="pe-note"><strong>${p.search_enabled?'Supplier connection configured':'Amazon Business: waiting for access'}</strong><small>${p.credentials_configured?'Server credentials present.':'No Amazon Business credentials configured.'} ${esc(p.approval_state.replaceAll('_',' '))}. No automatic purchasing.</small></div>
 <p>Customer catalog: <strong>MACEDA DECORATIONS</strong>. Supplier costs, references and imagery stay internal. Your inventory spreadsheet is read-only here.</p>
 <div class="pe-actions"><button class="secondary" id="peScan">Check review queue</button><a class="secondary" href="https://docs.google.com/spreadsheets/d/1u7hnYI0b0_5AHJFu23kcGDtmLXGxxUiIykdUjNn13Mo/edit#gid=1724586036" target="_blank" rel="noopener">Open inventory sheet</a></div>
 </section>
 <section class="panel"><h3>Decoration catalog</h3><p>${j.variants.length} exact variants · ${j.flags.length} open review flags · ${j.queue.length} refresh requests</p>
 <div class="pe-grid">${j.variants.map(v=>`<article class="pe-card"><h3>${esc(v.customer_name)}</h3>${status(v.status)}<small>${esc(v.variant_code)} · ${esc(v.color)} · ${v.width_m?esc(v.width_m)+' × '+esc(v.height_m)+' m':'Dimensions required'}</small><small>${esc(v.qualification_state)} · ${v.customer_visible?'Catalog visibility enabled':'Customer hidden'}</small><small>${esc(v.qualification_errors.join(', '))}</small><div class="pe-actions"><button class="secondary" data-edit="${v.id}">Edit</button><button class="secondary" data-stock="${v.id}">Inventory</button><button class="primary" data-approve="${v.id}" ${v.qualification_errors.length?'disabled':''}>Approve for catalog</button><button class="secondary" data-hide="${v.id}">Hide</button></div></article>`).join('')||'<p>No exact products approved yet. Existing visualizer decorations remain concepts.</p>'}</div>
 <details id="peNewProduct"><summary>Add a Maceda product</summary><form id="peProductForm" class="pe-grid" style="margin-top:16px">${input('Maceda product ID','maceda_product_id','','placeholder="ML-WREATH-72" required pattern="ML-[A-Z0-9-]+"')}${input('Maceda product name','customer_name','','required')}${select('Category','category_id',options(j.categories))}<div class="pe-actions"><button class="primary">Create product record</button></div></form></details>
 <details id="peVariantDetails"><summary>Add or edit an exact variant</summary><form id="peVariantForm" class="pe-grid" style="margin-top:16px"><input type="hidden" name="id"><input type="hidden" name="supplier_item_id">
 ${select('Maceda product','product_id',options(j.products,'id','customer_name'))}${input('Maceda variant code','variant_code','','placeholder="ML-WREATH-72-WW" required')}
 ${input('Customer-facing variant name','customer_name','','required')}${select('Category','category_id',options(j.categories))}${input('Color / variant','color','','placeholder="Warm White" required')}
 ${input('Width in meters','width_m','','type="number" min="0.001" max="100" step="any"')}${input('Height in meters','height_m','','type="number" min="0.001" max="100" step="any"')}${input('Depth in meters (optional)','depth_m','','type="number" min="0.001" max="100" step="any"')}
 ${input('Dimension source / measurement','dimension_source','','placeholder="6 ft = 1.8288 m; manufacturer drawing or measured"')}${input('Outdoor rating evidence','outdoor_rating')}
 ${input('Approved installation zones (comma separated)','allowed_zones','','placeholder="front_door, windows"')}${input('Electrical specifications / not applicable','electrical_notes')}
 <label><input type="checkbox" name="electrical_reviewed">Electrical suitability reviewed</label>
 ${input('Maceda-owned customer photo URL (HTTPS)','customer_image_url','','type="url"')}${select('Public image rights','image_rights','<option value="unverified">Unverified — customer hidden</option><option value="maceda_owned">Maceda-owned photography</option>')}${input('Image ownership evidence','image_rights_evidence')}
 <p class="wide">Supplier imagery is not copied into customer cards. Saving changes resets qualification and hides the variant until reviewed again.</p><div class="pe-actions"><button class="primary">Save for review</button><button class="secondary" type="reset">Clear form</button></div></form></details>
 <div id="peStockPanel"></div></section>
 <section class="panel"><h3>Approved category discovery</h3><p>Searches create internal candidates only. Each product must pass Maceda review before it can be selected.</p><div class="pe-grid">${j.categories.map(c=>`<div class="pe-card"><strong>${esc(c.name)}</strong><small>${esc(c.search_terms)}</small><button class="secondary" data-search="${c.id}" ${p.search_enabled?'':'disabled'}>Find candidates</button></div>`).join('')}</div>
 <div class="pe-actions"><button class="secondary" id="peCandidates">Review imported candidates</button><button class="secondary" id="peCarts" ${p.cart_read_enabled?'':'disabled'}>Review Business carts</button></div><div id="peSupplierResults"></div></section>
 <section class="panel"><h3>Review a customer design</h3><p>Map concept decorations to exact qualified variants before recording customer acceptance. Product size comes from dimensions; measured house calibration is required for scaled rendering.</p>
 <form id="peReviewForm" class="pe-grid">${input('Quote record ID','quote_id','','required')}${input('Job reference (optional)','external_job_reference')}${input('Customer reference (optional)','external_customer_reference')}
 ${select('Exact variant','variant_id',options(j.variants.filter(v=>v.qualification_state==='approved'&&['in_maceda_inventory','available_to_order'].includes(v.status)),'id','customer_name'))}${input('Quantity','quantity',1,'type="number" min="1" max="1000" required')}${input('Installation zone','zone_id','','placeholder="front_door" required')}
 <div class="wide" id="peReviewLines"></div><div class="pe-actions"><button class="secondary" type="button" id="peAddLine">Add product line</button><button class="primary">Save reviewed design</button></div></form>
 <div class="pe-list" style="margin-top:20px">${j.designs.map(d=>`<article class="pe-card"><strong>Design revision ${d.design_revision}</strong><small>Quote ${esc(d.quote_id)} · ${d.accepted_at?'Acceptance recorded':'Awaiting customer acceptance'}</small><small>${(d.pe_design_lines||[]).map(l=>esc(l.quantity)+' × '+esc(l.product_snapshot.customer_name)).join(' · ')}</small><div class="pe-actions"><button class="secondary" data-quote="${d.quote_id}">Open customer record</button><button class="secondary" data-accept="${d.id}">Record acceptance</button><button class="primary" data-procure="${d.id}" ${d.accepted_at?'':'disabled'}>Build procurement list</button></div><div id="peAccept-${d.id}"></div></article>`).join('')}</div></section>
 <section class="panel"><h3>Procurement & reservations</h3><p>Inventory is used first. Purchase quantities require a fresh exact-variant supplier check after the deposit. You make every purchase manually.</p><div class="pe-list">${j.procurements.map(pr=>`<article class="pe-card">${status(pr.state)}${(pr.pe_procurement_lines||[]).map(l=>`<p>${esc(j.variants.find(v=>v.id===l.variant_id)?.customer_name||l.variant_id)}: ${l.required_qty} required · ${l.owned_allocated_qty} reserved · ${l.purchase_qty} to purchase<br>${status(l.state)}<small>Internal unit cost: ${l.supplier_snapshot?.unit_cost==null?'Needs fresh check':esc(l.supplier_snapshot.currency)+' '+esc(l.supplier_snapshot.unit_cost)}</small>${purchaseLink(l.supplier_snapshot?.purchase_reference)}</p>`).join('')}${(pr.pe_reservations||[]).filter(r=>['reserved','installed'].includes(r.state)).map(r=>`<button class="secondary" data-return="${r.id}">Record ${r.quantity} returned to storage</button>`).join('')}</article>`).join('')||'<p>No procurement lists yet.</p>'}</div></section>
 <section class="panel"><h3>Needs your review</h3>${j.flags.map(f=>`<p>${esc(f.reason.replaceAll('_',' '))}<small>Design ${esc(f.design_id)} · variant ${esc(f.variant_id)}</small></p>`).join('')||'<p>No product review flags.</p>'}<small>Existing designs are preserved when products change. Alternatives require your approval; nothing is silently substituted.</small><h4>Approved alternatives</h4>${(j.alternatives||[]).map(a=>`<p>${esc(j.variants.find(v=>v.id===a.variant_id)?.customer_name||a.variant_id)} → ${esc(j.variants.find(v=>v.id===a.alternative_variant_id)?.customer_name||a.alternative_variant_id)}<small>${esc(a.notes)} · Recheck availability and obtain customer approval before substitution.</small></p>`).join('')||'<p>No alternatives approved yet.</p>'}</section></div>`;
 el('peScan').onclick=()=>action(()=>call('scan_refresh'),'Review queue checked.');
 const productForm=el('peProductForm');productForm.onsubmit=e=>{e.preventDefault();action(()=>call('create_product',Object.fromEntries(new FormData(productForm))),'Maceda product created.')};
 const vf=el('peVariantForm');vf.onsubmit=e=>{e.preventDefault();let b=Object.fromEntries(new FormData(vf));b.allowed_zones=b.allowed_zones.split(',').map(x=>x.trim()).filter(Boolean);b.electrical_reviewed=vf.elements.electrical_reviewed.checked;action(()=>call('save_variant',b),'Variant saved for review.')};
 document.querySelectorAll('[data-edit]').forEach(n=>n.onclick=()=>{const v=j.variants.find(v=>v.id===n.dataset.edit);Object.entries(v).forEach(([k,x])=>{if(vf.elements[k]){if(vf.elements[k].type==='checkbox')vf.elements[k].checked=x===true;else vf.elements[k].value=Array.isArray(x)?x.join(', '):x??''}});vf.elements.electrical_notes.value=v.electrical_specifications?.notes||'';el('peVariantDetails').open=true;vf.scrollIntoView({behavior:'smooth',block:'start'})});
 document.querySelectorAll('[data-approve]').forEach(n=>n.onclick=()=>action(()=>call('approve_variant',{id:n.dataset.approve,customer_visible:true}),'Variant approved. Availability still controls selection.'));
 document.querySelectorAll('[data-hide]').forEach(n=>n.onclick=()=>action(()=>call('hide_variant',{id:n.dataset.hide}),'Variant hidden; existing designs preserved.'));
 document.querySelectorAll('[data-stock]').forEach(n=>n.onclick=()=>{const v=j.variants.find(v=>v.id===n.dataset.stock),inv=j.inventory.find(i=>i.variant_id===v.id);el('peStockPanel').innerHTML=`<form id="peStockForm" class="pe-grid" style="margin-top:20px"><h3 class="wide">Verified stock: ${esc(v.customer_name)}</h3>${input('Total reusable units owned (including reservations)','quantity',inv?.quantity_owned||0,'type="number" min="0" required')}${input('Count/source evidence','source_reference',inv?.source_reference||'','required')}${input('Storage location','storage_location',inv?.storage_location||'')}<div class="pe-actions"><button class="primary">Save verified count</button></div></form>`;el('peStockForm').onsubmit=e=>{e.preventDefault();action(()=>call('set_inventory',{variant_id:v.id,...Object.fromEntries(new FormData(e.target))}),'Verified inventory saved. Spreadsheet unchanged.')};el('peStockPanel').scrollIntoView({behavior:'smooth'})});
 document.querySelectorAll('[data-search]').forEach(n=>n.onclick=()=>action(()=>call('search_category',{category_id:n.dataset.search}),'Candidates saved internally.'));
 el('peCandidates').onclick=async()=>{try{const r=await authFetch(endpoint+'?view=candidates');el('peSupplierResults').innerHTML='<p>Internal supplier records — not customer catalog products.</p>'+r.items.map(i=>'<div class="pe-card"><strong>'+esc(i.title)+'</strong><small>'+esc(i.environment)+' · '+esc(i.external_product_id)+' · '+esc(i.availability)+'</small><small>Exact variant and delivery '+(i.exact_variant_verified&&i.delivery_verified?'verified':'need review')+'</small></div>').join('');if(!r.items.length)el('peSupplierResults').innerHTML='<p>No supplier candidates imported.</p>'}catch(e){toast(e.message,'bad')}};
 el('peCarts').onclick=async()=>{try{const r=await authFetch(endpoint+'?view=carts');el('peSupplierResults').innerHTML='<p>Only carts available through the authorized Business Cart API are shown.</p>'+(r.data.cartDetailsList||[]).map(c=>'<button class="secondary" data-cart="'+esc(c.id)+'">Review '+esc(c.id)+'</button>').join('');document.querySelectorAll('[data-cart]').forEach(n=>n.onclick=async()=>{try{const res=await authFetch(endpoint+'?view=cart_items&cart_id='+encodeURIComponent(n.dataset.cart));el('peSupplierResults').innerHTML=(res.data.items||[]).map(i=>'<div class="pe-card"><strong>'+esc(i.productIdentifier)+'</strong><small>Quantity '+esc(i.quantity)+'</small><select class="field" id="peCartCategory-'+esc(i.itemId)+'">'+options(j.categories)+'</select><button class="secondary" data-cart-import="'+esc(i.itemId)+'">Import as internal candidate</button></div>').join('');document.querySelectorAll('[data-cart-import]').forEach(b=>b.onclick=()=>action(()=>call('import_cart_items',{cart_id:n.dataset.cart,item_ids:[b.dataset.cartImport],category_id:el('peCartCategory-'+b.dataset.cartImport).value}),'Cart item imported for review.'))}catch(e){toast(e.message,'bad')}})}catch(e){toast(e.message,'bad')}};
 let reviewLines=[];const rf=el('peReviewForm');const draftLine=()=>({variant_id:rf.elements.variant_id.value,quantity:Number(rf.elements.quantity.value),zone_id:rf.elements.zone_id.value.trim()});
 el('peAddLine').onclick=()=>{const l=draftLine();if(!l.variant_id||!l.zone_id||l.quantity<1){toast('Choose an approved variant, quantity and zone.','bad');return}reviewLines.push(l);el('peReviewLines').innerHTML=reviewLines.map((l,i)=>'<p>'+esc(l.quantity)+' × '+esc(j.variants.find(v=>v.id===l.variant_id)?.customer_name)+' · '+esc(l.zone_id)+' <button type="button" data-remove-line="'+i+'">Remove</button></p>').join('');document.querySelectorAll('[data-remove-line]').forEach(b=>b.onclick=()=>{reviewLines.splice(Number(b.dataset.removeLine),1);b.parentElement.remove()})};
 rf.onsubmit=e=>{e.preventDefault();const b=Object.fromEntries(new FormData(rf));b.lines=reviewLines.length?reviewLines:[draftLine()];action(()=>call('review_design',b),'Exact product design saved for customer acceptance.')};
 document.querySelectorAll('[data-quote]').forEach(n=>n.onclick=()=>openDetail(n.dataset.quote));
 document.querySelectorAll('[data-accept]').forEach(n=>n.onclick=()=>{const container=el('peAccept-'+n.dataset.accept);container.innerHTML='<form class="pe-actions"><label>Customer acceptance reference<input class="field" name="evidence" required minlength="5" placeholder="Signed quote or approval message reference"></label><button class="primary">Record acceptance</button></form>';container.querySelector('form').onsubmit=e=>{e.preventDefault();action(()=>call('record_acceptance',{design_id:n.dataset.accept,evidence:new FormData(e.target).get('evidence')}),'Acceptance recorded.')}});
 document.querySelectorAll('[data-procure]').forEach(n=>n.onclick=()=>action(()=>call('build_procurement',{design_id:n.dataset.procure}),'Procurement list built. No purchase was made.'));
 document.querySelectorAll('[data-return]').forEach(n=>n.onclick=()=>action(()=>call('return_inventory',{id:n.dataset.return}),'Inventory returned to storage.'));
}
